### PR TITLE
Only create one socket listener

### LINKED ISSUE #174: Socket errors when having multiple data sources
```java
Error starting CamelContext (camel-1) due to exception thrown: Failed to start route manzan_msg:watcher3socket because of Multiple consumers for the same endpoint is not allowed: netty://tcp://0.0.0.0:8080?sync=false
org.apache.camel.FailedToStartRouteException: Failed to start route manzan_msg:watcher3socket because of Multiple consumers for the same endpoint is not allowed: netty://tcp://0.0.0.0:8080?sync=false
        at org.apache.camel.impl.engine.InternalRouteStartupManager.doStartOrResumeRouteConsumers(InternalRouteStartupManager.java:357) ~[manzan.jar:?]
        at org.apache.camel.impl.engine.InternalRouteStartupManager.doStartRouteConsumers(InternalRouteStartupManager.java:319) ~[manzan.jar:?]
        at org.apache.camel.impl.engine.InternalRouteStartupManager.safelyStartRouteServices(InternalRouteStartupManager.java:213) ~[manzan.jar:?]
        at org.apache.camel.impl.engine.InternalRouteStartupManager.doStartOrResumeRoutes(InternalRouteStartupManager.java:147) ~[manzan.jar:?]
        at org.apache.camel.impl.engine.AbstractCamelContext.doStartCamel(AbstractCamelContext.java:3301) ~[manzan.jar:?]
        at org.apache.camel.impl.engine.AbstractCamelContext.doStartContext(AbstractCamelContext.java:2952) ~[manzan.jar:?]
        at org.apache.camel.impl.engine.AbstractCamelContext.doStart(AbstractCamelContext.java:2903) ~[manzan.jar:?]
        at org.apache.camel.support.service.BaseService.start(BaseService.java:119) ~[manzan.jar:?]
        at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2587) ~[manzan.jar:?]
        at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:253) ~[manzan.jar:?]
        at com.github.theprez.manzan.ManzanMainApp.main(ManzanMainApp.java:65) ~[manzan.jar:?]
```

### PR DESCRIPTION
**Pull request by jonnyz32**
Fixes #174 . Tested manually and with automated tests.

### CODE REVIEW

File: camel/src/main/java/com/github/theprez/manzan/configuration/DataConfig.java [hunk 1]
```diff
@@ -104,7 +91,62 @@ public synchronized Map<String, ManzanRoute> getRoutes() throws IOException, AS4
...
+            String destString = createRecipientList(destinations);
+            formatMap.put(id.toUpperCase(), format);
+            destMap.put(id.toUpperCase(), destString);
+
+            String sqlRouteName = name + "sql";
+            ret.put(sqlRouteName, new WatchMsgEventSql(sqlRouteName, id, format, destinations, schema, eventType, interval, numToProcess));
+            WatchStarter ws = new WatchStarter(id, strwch);
+            ws.strwch();
+
+            if (i == watchEvents.size() - 1){
```
Comment (SanjulaGanepola) [inline camel/src/main/java/com/github/theprez/manzan/configuration/DataConfig.java:144]: Can we just move this outside the look and do this if `watchEvents.size() > 0` to avoid having to check this on each iteration?

File: camel/src/main/java/com/github/theprez/manzan/routes/event/WatchMsgEventSockets.java [hunk 2]
```diff
@@ -1,28 +1,26 @@
...
 import com.github.theprez.manzan.ManzanEventType;
 import com.github.theprez.manzan.ManzanMessageFormatter;
 import com.github.theprez.manzan.routes.ManzanRoute;
 
 public class WatchMsgEventSockets extends ManzanRoute {
 
-    private final ManzanMessageFormatter m_formatter;
+//    private final ManzanMessageFormatter m_formatter;
+    private final Map<String, String> m_formatMap;
+    final Map<String, String> m_destMap;
```
Comment (SanjulaGanepola) [inline camel/src/main/java/com/github/theprez/manzan/routes/event/WatchMsgEventSockets.java:15]:
```suggestion
    private final Map<String, String> m_destMap;
```

File: camel/src/main/java/com/github/theprez/manzan/routes/event/WatchMsgEventSockets.java [hunk 3]
```diff
@@ -1,28 +1,26 @@
...
 
-import com.github.theprez.jcmdutils.StringUtils;
 import com.github.theprez.manzan.ManzanEventType;
 import com.github.theprez.manzan.ManzanMessageFormatter;
 import com.github.theprez.manzan.routes.ManzanRoute;
 
 public class WatchMsgEventSockets extends ManzanRoute {
 
-    private final ManzanMessageFormatter m_formatter;
+//    private final ManzanMessageFormatter m_formatter;
```
Comment (SanjulaGanepola) [inline camel/src/main/java/com/github/theprez/manzan/routes/event/WatchMsgEventSockets.java:13]:
```suggestion
```

File: camel/src/main/java/com/github/theprez/manzan/routes/event/WatchMsgEventSockets.java [hunk 4]
```diff
@@ -32,16 +30,22 @@ public void configure() {
...
             .marshal().json(true) //TODO: skip this if we are applying a format
             .setBody(simple("${body}\n"))
             .process(exchange -> {
-                if (null != m_formatter) {
+                String sessionId = exchange.getIn().getHeader("session_id", String.class);
+                String format = m_formatMap.get(sessionId);
+                if (format != null) {
+                    ManzanMessageFormatter m_formatter = new ManzanMessageFormatter(format);
                     exchange.getIn().setBody(m_formatter.format(getDataMap(exchange)));
+                    String destinations = m_destMap.get(sessionId); // Get destinations from m_destMap
```
Comment (SanjulaGanepola) [inline camel/src/main/java/com/github/theprez/manzan/routes/event/WatchMsgEventSockets.java:43]: Shouldn't this be outside the parent `if` since `format` is optional?

File: camel/src/main/java/com/github/theprez/manzan/routes/event/WatchMsgEventSockets.java [hunk 5]
```diff
@@ -32,16 +30,22 @@ public void configure() {
...
+                    exchange.getIn().setHeader("destinations", destinations);
                 }
             })
-            .recipientList(constant(getRecipientList())).parallelProcessing().stopOnException().end();
+                .recipientList(header("destinations"))
+                .parallelProcessing().stopOnException();
```
Comment (SanjulaGanepola) [inline camel/src/main/java/com/github/theprez/manzan/routes/event/WatchMsgEventSockets.java:48]: Is the previous `.end()` needed?

**Review by SanjulaGanepola — CHANGES_REQUESTED** [review]

File: camel/src/main/java/com/github/theprez/manzan/routes/event/WatchMsgEventSockets.java (hunk 4 above)
Comment (jonnyz32) [reply camel/src/main/java/com/github/theprez/manzan/routes/event/WatchMsgEventSockets.java]: Good catch. Fixed this now.

File: camel/src/main/java/com/github/theprez/manzan/routes/event/WatchMsgEventSockets.java (hunk 5 above)
Comment (jonnyz32) [reply camel/src/main/java/com/github/theprez/manzan/routes/event/WatchMsgEventSockets.java]: Maybe.. I've added it back, just in case

File: camel/src/main/java/com/github/theprez/manzan/configuration/DataConfig.java (hunk 1 above)
Comment (jonnyz32) [reply camel/src/main/java/com/github/theprez/manzan/configuration/DataConfig.java]: Moved after for loop now
